// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyiA21VV2fHILCINiYTFYQTXlyU8kdOV4',
    appId: '1:179086960875:web:ef4e87c0343458bdfaf6ae',
    messagingSenderId: '179086960875',
    projectId: 'reddit-ed-39c2d',
    authDomain: 'reddit-ed-39c2d.firebaseapp.com',
    storageBucket: 'reddit-ed-39c2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVoygLY-2rjSETjeHh-eKeTaCdfwiS36Y',
    appId: '1:179086960875:android:85fbdeaf54ac36c8faf6ae',
    messagingSenderId: '179086960875',
    projectId: 'reddit-ed-39c2d',
    storageBucket: 'reddit-ed-39c2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj65noMGArxzhrhnq7RKlW0ZOAtavhrZ0',
    appId: '1:179086960875:ios:cb90c5bf8b394e88faf6ae',
    messagingSenderId: '179086960875',
    projectId: 'reddit-ed-39c2d',
    storageBucket: 'reddit-ed-39c2d.appspot.com',
    iosClientId: '179086960875-k2ro06tcak51nicj6jhqs1d3ar4v1d9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditEd',
  );
}
